# -*- coding: utf-8 -*-
"""scood airlines

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TcVQ0Ck0xacIXAMr3DUJqjob4AOE69Ih
"""

import streamlit as st
status = True
yes = "work"
if st.button("plane"):
    st.write(yes)
if st.button("no plane"):
    no = "plane crashe"
    st.write(no)
name = st.text_input("Name")
if name == ' ':
    st.error("please enter a valid name")

for loop in range(len(name)):
    if name[loop].isdigit():
        status = False
if status == False:
    st.warning("why is there number in your name")


if st.button("balloon (DO NOT PRESS)"):
    for loop in range(100):
      st.balloons()
      st.toast("balloon")


seat = 'a'
a,b,c,d,e,f,g,h = st.columns(8)


with a:
    seat='a'
    st.button(f"{seat}1"),st.button(f"{seat}2"),st.button(f"{seat}3"),st.button(f"{seat}4"),st.button(f"{seat}5"),st.button(f"{seat}6"),st.button(f"{seat}7"),st.button(f"{seat}8"),

with b:
    seat = 'b'
    st.button(f"{seat}1"),st.button(f"{seat}2"),st.button(f"{seat}3"),st.button(f"{seat}4"),st.button(f"{seat}5"),st.button(f"{seat}6"),st.button(f"{seat}7"),st.button(f"{seat}8")

with c:
    seat = 'c'
    st.button(f"{seat}1"),st.button(f"{seat}2"),st.button(f"{seat}3"),st.button(f"{seat}4"),st.button(f"{seat}5"),st.button(f"{seat}6"),st.button(f"{seat}7"),st.button(f"{seat}8")
with d:
    seat = 'd'
    st.button(f"{seat}1"),st.button(f"{seat}2"),st.button(f"{seat}3"),st.button(f"{seat}4"),st.button(f"{seat}5"),st.button(f"{seat}6"),st.button(f"{seat}7"),st.button(f"{seat}8")
with e:
    seat = 'e'
    st.button(f"{seat}1"),st.button(f"{seat}2"),st.button(f"{seat}3"),st.button(f"{seat}4"),st.button(f"{seat}5"),st.button(f"{seat}6"),st.button(f"{seat}7"),st.button(f"{seat}8")
with f:
    seat = 'f'
    st.button(f"{seat}1"),st.button(f"{seat}2"),st.button(f"{seat}3"),st.button(f"{seat}4"),st.button(f"{seat}5"),st.button(f"{seat}6"),st.button(f"{seat}7"),st.button(f"{seat}8")
with g:
    seat = 'g'
    st.button(f"{seat}1"),st.button(f"{seat}2"),st.button(f"{seat}3"),st.button(f"{seat}4"),st.button(f"{seat}5"),st.button(f"{seat}6"),st.button(f"{seat}7"),st.button(f"{seat}8")
with h:
    seat = 'h'
    st.button(f"{seat}1"),st.button(f"{seat}2"),st.button(f"{seat}3"),st.button(f"{seat}4"),st.button(f"{seat}5"),st.button(f"{seat}6"),st.button(f"{seat}7"),st.button(f"{seat}8")