# -*- coding: utf-8 -*-
"""scood airlines 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zf565maSOpGIf8SFhnhudKf5rxZjPHJ1
"""

#this one is new
import streamlit as st

st.markdown("""
<style>
.stApp{
    background-color:#F7FE00;
}
""")
def SeatSel():#it returns a dictionary with name phone and email and seat
  st.snow()
  if 'page_state' not in st.session_state:
      st.session_state.page_state = 'buy_plane_page'

  st.header('Welcome to scood airlines')
  st.subheader("Flights : to langkawi (you will die)")

  if st.session_state.page_state == 'buy_plane_page':
      if st.button("buy a plane"):
          st.session_state.page_state = 'ship_plane_page'
          st.rerun()

  elif st.session_state.page_state == 'ship_plane_page':
      st.success("tank for buying scood plane")
      if st.button("ship plane"):
          st.success(f"great your plane has been shipped to (11°04'37.9'N 174°46'03.4'E)")


  if 'Customers' not in st.session_state:
    st.session_state['Customers']=[]
  if 'Submit' not in st.session_state:
    st.session_state['Submit']=0
  if 'AmountCustomer' not in st.session_state:
    st.session_state['AmountCustomer']=0
  if 'SeatTemp' not in st.session_state:
    st.session_state['SeatTemp']=0

  if st.button('reset (the plane crashed)'):
    st.session_state['Submit']=0

  if st.session_state['Submit']==0:
    AmountCustomer=int(st.number_input('amount of customer',step=1,min_value=1))
    if st.button('sumbmit1'):
      st.session_state.AmountCustomer=AmountCustomer
      st.session_state['Submit']=1
      st.rerun()

  if st.session_state['Submit']==1:
    CustomersTemp=[]
    for loop in range(st.session_state.AmountCustomer):
      st.title(f'please key in your details for free steeling (customer{loop+1})')
      Customer=[]
      Customer.append(st.text_input(f'(customer{loop+1}) put your name',placeholder=''))
      Customer.append(st.text_input(f'(customer{loop+1}) phone number (with the +65 thingy)',placeholder='+65[space]12345678'))
      Customer.append(st.text_input(f'(customer{loop+1}) email',placeholder='iugawdhigdiagiu@akjdghjdj.com'))
      errors=[]
      #put error
      if Customer[0]=='':
        errors.append('put your name')
      else:
        if any(char.isdigit() for char in Customer[0]):
          errors.append('why does your name have number')
      if Customer[1]=='':
        errors.append('put your phoen number')
      else:
        if (Customer[1])[0]!='+':
          errors.append('put the +65 thing')
        if any((not char.isdigit() and char!='+') for char in Customer[1]):
          errors.append('why is there not number in your phoen number')
      if Customer[2]=='':
        errors.append('put you email or else you get mailed to north korea')
      elif not(any(char=='@' for char in Customer[2])):
        errors.append('put @')

      #display
      if errors==[]:
        st.success('ok')
        CustomersTemp.append({'name':Customer[0],'phone':Customer[1],'email':Customer[2]})

      else:
        st.error(f'screw you ({')'.join(errors)})')

    if len(CustomersTemp)==st.session_state['AmountCustomer']:
      if st.button('sumbmit2'):
        st.session_state['Customers']=CustomersTemp
        st.session_state['Submit']=2
        st.rerun()

  if st.session_state['Submit']==2: #(seat)
    for loop in range(st.session_state['SeatTemp']):
      try:
        st.write(f'(done) {st.session_state['Customers'][loop]['name']} (customer{loop+1})(selected {st.session_state['Customers'][loop]['seat']})')
      except KeyError:
        pass
    if st.session_state['SeatTemp']>len(st.session_state['Customers'])-1:
      st.success('you got scammed you are getting sent to squid game')
      for loop in range(50):
        st.balloons()
      return(st.session_state['Customers'])
    else:
      st.title(f'select seat for {st.session_state['Customers'][st.session_state['SeatTemp']]['name']} (customer{st.session_state['SeatTemp']+1})')
      SeatColAmount=6
      SeatRowAmount=20
      SeatCol=st.columns(SeatColAmount)
      for LoopCol in range(len(SeatCol)):
        with SeatCol[LoopCol]:
          for LoopRow in range(SeatRowAmount):
            if st.button(f'{chr(ord('a')+LoopCol)}{LoopRow+1}'):
              st.session_state['Customers'][st.session_state['SeatTemp']]['seat']=f'{chr(ord('a')+LoopCol)}{LoopRow+1}'
              st.session_state['SeatTemp']+=1




SeatSel()