# -*- coding: utf-8 -*-
"""scood airlines

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TcVQ0Ck0xacIXAMr3DUJqjob4AOE69Ih
"""

import streamlit as st
backgroundColor="black"
def PutStuffs(AmountCustomer):#it returns a dictionary with name(as key) phone and email (phone and email are inside another dictionary btw)
  Customers={}
  val=0
  for loop in range(AmountCustomer):
    st.title(f'please key in your details for free steeling(customer{loop})')
    Customer=[]
    Customer.append(st.text_input(f'(customer{loop}) put your name',placeholder=''))
    Customer.append(st.text_input(f'(customer{loop}) phone number (with the +65 thingy)',placeholder='+65[space]12345678'))
    Customer.append(st.text_input(f'(customer{loop}) email',placeholder='iugawdhigdiagiu@akjdghjdj.com'))
    errors=[]
    #put error
    if Customer[0]=='':
      errors.append('put your name')
    else:
      if any(char.isdigit() for char in Customer[0]):
        errors.append('why does your name have number')
    if Customer[1]=='':
      errors.append('put your phoen number')
    else:
      if (Customer[1])[0]!='+':
        errors.append('put the +65 thing')
      if any(char.isalpha() for char in Customer[1])and(char!='+'):
        errors.append('why is there not number in your phoen number')
    if Customer[2]=='':
      errors.append('put you email or else you get mailed to north korea')
    elif not(any(char=='@' for char in Customer[2])):
      errors.append('put @')

    #display
    if errors==[]:
      st.success('ok')
      Customers[Customer[0]]=({'phone':Customer[1],'email':Customer[2]})
      val+=1
    else:
      st.error(f'screw you ({')('.join(errors)})')

  if AmountCustomer==0:
    st.error('screw you (put more than 0 customer)')
  elif val==AmountCustomer:
    if st.button('sumbmit'):
      for loop in range(50):
        st.balloons()
      return(Customers)
status = True
yes = "work"
if st.button("plane"):
    st.write(yes)
if st.button("no plane"):
    no = "plane crashe"
    st.write(no)

name = st.text_input("Name")

if name == ' ':
    st.error("please enter a valid name")

for char in name:
    if char.isdigit():
        status = False
if not status:
    st.warning("why is there number in your name")


if st.button("balloon (DO NOT PRESS)"):
    for loop in range(100):
      st.balloons()
      st.toast("balloon")

st.write("### Economy Class")
st.write("          Back")

# Initialize session state for selected seats if not already present
if 'selected_seats' not in st.session_state:
    st.session_state.selected_seats = set()

# economy
seat_rows = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

# seat label
for row_label in seat_rows:
    st.write(f"**Row {row_label.upper()}**")

    # seat
    seat_display_cols = st.columns([1, 1, 2, 1, 1, 1, 2, 1, 1])

    seat_idx_counter = 0 # Count seat

    # Section 1: 2 seats (columns 1, 2)
    for col_num in [1, 2]:
        seat_id = f"{row_label}{col_num}"
        with seat_display_cols[seat_idx_counter]:
            checked = seat_id in st.session_state.selected_seats
            if st.checkbox(seat_id, key=f"checkbox_{seat_id}", value=checked):
                if seat_id not in st.session_state.selected_seats:
                    st.session_state.selected_seats.add(seat_id)
            else:
                if seat_id in st.session_state.selected_seats:
                    st.session_state.selected_seats.remove(seat_id)
        seat_idx_counter += 1 # Corrected increment

    seat_idx_counter += 1 # Skip aisle column (at index 2)

    # Section 2: 3 seats (columns 3, 4, 5)
    for col_num in [3, 4, 5]:
        seat_id = f"{row_label}{col_num}"
        with seat_display_cols[seat_idx_counter]:
            checked = seat_id in st.session_state.selected_seats
            if st.checkbox(seat_id, key=f"checkbox_{seat_id}", value=checked):
                if seat_id not in st.session_state.selected_seats:
                    st.session_state.selected_seats.add(seat_id)
            else:
                if seat_id in st.session_state.selected_seats:
                    st.session_state.selected_seats.remove(seat_id)
        seat_idx_counter += 1 # Corrected increment

    seat_idx_counter += 1 # Skip aisle column (at index 6)

    # Section 3: 2 seats (columns 6, 7)
    for col_num in [6, 7]:
        seat_id = f"{row_label}{col_num}"
        with seat_display_cols[seat_idx_counter]:
            checked = seat_id in st.session_state.selected_seats
            if st.checkbox(seat_id, key=f"checkbox_{seat_id}", value=checked):
                if seat_id not in st.session_state.selected_seats:
                    st.session_state.selected_seats.add(seat_id)
            else:
                if seat_id in st.session_state.selected_seats:
                    st.session_state.selected_seats.remove(seat_id)
        seat_idx_counter += 1

st.write("### Business Class (3-4 Layout)")

business_seat_rows = ['z', 'y', 'x']
for row_label in business_seat_rows:
    st.write(f"**Row {row_label.upper()}**")

    # create column
    seat_display_cols_business = st.columns([1, 1, 1, 3, 1, 1, 1])

    seat_idx_counter_business = 0

    # Section 1: 3 seats (columns 1, 2, 3)
    for col_num in [1, 2, 3]:
        seat_id = f"{row_label}{col_num}"
        with seat_display_cols_business[seat_idx_counter_business]:
            checked = seat_id in st.session_state.selected_seats
            if st.checkbox(seat_id, key=f"checkbox_{seat_id}", value=checked):
                if seat_id not in st.session_state.selected_seats:
                    st.session_state.selected_seats.add(seat_id)
            else:
                if seat_id in st.session_state.selected_seats:
                    st.session_state.selected_seats.remove(seat_id)
        seat_idx_counter_business += 1

    seat_idx_counter_business += 1 # Skip aisle column

    # right side
    for col_num in [4, 5, 6]:
        seat_id = f"{row_label}{col_num}"
        with seat_display_cols_business[seat_idx_counter_business]:
            checked = seat_id in st.session_state.selected_seats
            if st.checkbox(seat_id, key=f"checkbox_{seat_id}", value=checked):
                if seat_id not in st.session_state.selected_seats:
                    st.session_state.selected_seats.add(seat_id)
            else:
                if seat_id in st.session_state.selected_seats:
                    st.session_state.selected_seats.remove(seat_id)
        seat_idx_counter_business += 1
st.write("              Back")
# Display
st.write(f"### Total seats booked: {len(st.session_state.selected_seats)}")

# Display selected seats details
if st.session_state.selected_seats:
    st.write("### Selected Seat Details:")
    st.write(sorted(list(st.session_state.selected_seats)))
else:
    st.write("No seats selected yet.")

Customers=PutStuffs(len(st.session_state.selected_seats))
for loop in range(1):
    st.snow()