# -*- coding: utf-8 -*-
"""group 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ozS8mOZ_3b0yF91Ri5RAKm5yjxNt7wTJ
"""

# Group 3
# Members
# Leader - ziyi
# Coders - zhixiang, chazz, ashton
# Testers - idk



# zhi xiang

# chazz

# zi yi
import streamlit as st
formula = st.text_input("Enter a math equation with +,-,*,/")
formula = formula.replace(" ","")

first = ""
last = ""
operation = ""
temp = -1
for i in range(len(formula)):
  if formula[i].isdigit() == True:
    first += str(formula[i])
  elif formula[i].isdigit() == False:
    operation = str(formula[i])
    temp = i
    break
  else:
    st.write("Something bad happened")

if temp != -1:
  last = formula[temp+1:]
  if operation == "+":
    answer = float(first) + float(last)
  elif operation == "-":
    answer = float(first) - float(last)
  elif operation == "*":
    answer = float(first) * float(last)
  elif operation == "/":
    answer = float(first) / float(last)
  else:
    st.write("something else worse happened")

  if formula != "":
    st.write(f"The answer is {answer}")
  else:
    st.write("Maybe enter something correct")
else:
  st.write("No operator")

#