# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ozS8mOZ_3b0yF91Ri5RAKm5yjxNt7wTJ
"""

# Group 3
# Members
# Leader - me
# Coders - zhixiang, chazz, ashton
# Testers - idk

import streamlit as st
import pandas as pd
import numpy as np

# zhi xiang
import streamlit as st
st.title("Hello World")

# chazz

# zi yi
st.write("Hello World!")

#