# -*- coding: utf-8 -*-
"""admin_panel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EvZI-M1_KsuYmBkwPl1Xtb9rhbE7EIxu
"""

#admin terminal (aidan) 2/7 update fix
import streamlit as st
import time
import json
from functools import reduce
import operator


def WriteToJson(fp:str, value, *locations):
  with open(fp,"r+") as f:
    myFile = json.load(f)
    reduce(operator.getitem, locations[:-1], myFile)[locations[-1]] = value
    f.seek(0)
    json.dump(myFile, f, indent = 4)
    f.truncate()

movie_file = "file.json"

st.title("Silver Kampong Admin Terminal")

if "movies" not in st.session_state:
  st.session_state.movies = {}
if "show_new_movie" not in st.session_state:
  st.session_state.show_new_movie = False
if "show_preview_changes" not in st.session_state:
  st.session_state.show_preview_changes = False
if "download" not in st.session_state:
  st.session_state.download = False
if "loaded" not in st.session_state:
  st.session_state.loaded = False

def export(movie_dict):
  return json.dumps(movie_dict, indent=4)

myFile = st.file_uploader("Existing JSON Movie Details File", accept_multiple_files=False, type="json")
if myFile and st.session_state.loaded != True:
  st.session_state.movies = json.load(myFile)
  st.session_state.loaded = True
elif myFile not in st.session_state:
  st.session_state.loaded = False

movie_count = 0
for title in st.session_state.movies:
  movie_count += 1

metric_col1, metric_col2 = st.columns(2)
with metric_col1:
  st.metric("Movies", movie_count, border=True)
with metric_col2:
  st.metric("Revenue", "$0", border=True)

if st.button("New Movie"):
  st.session_state.show_new_movie = not st.session_state.show_new_movie

if st.session_state.show_new_movie:
  with st.form("new_movie_details"):
    title = st.text_input("Title: ", key="title_input")
    desc = st.text_input("Description: ", key="desc_input")
    photos = st.text_input("Image Link: ", key="photos_input")
    showtimes = st.selectbox("Showtimes: ", ("9.00 AM", "12.00 PM", "3.00 PM"))
    showtimes = str(showtimes)
    halls = st.selectbox("Halls: ", ("Cinema Hall 1", "Cinema Hall 2", "Cinema Hall 3"))
    halls = str(halls)
    saved = st.form_submit_button("Save Changes")
  if saved:
    if title:
        movie_details = {"desc": desc, "photos": photos, "showtimes": showtimes, "halls": halls}
        st.session_state.movies[title] = movie_details
        st.session_state.json = export(st.session_state.movies)
        st.session_state.download = True
        if st.session_state.loaded == True:
          WriteToJson(movie_file, movie_details, title)
          st.success(f"'{title}' has been saved!")
          time.sleep(1)
        else:
          st.warning("A file is not loaded. Your movie has not been saved.", icon="⚠️")
          time.sleep(3)
        st.rerun()


if st.session_state.download:
  st.download_button(label="Download JSON", data=st.session_state.json, file_name="file.json", mime="text/json", icon=":material/download:",)
  st.divider()


st.subheader("Your Movies")
for title, details in st.session_state.movies.items():
  with st.expander(title):
    st.header(f"{title}")
    st.caption(details.get("desc"))
    image = details.get("photos")
    if image:
      st.image(image, width=200)
    st.write(f"Hall: {details.get('halls')}")
    st.write(f"Showtime: {details.get('showtimes')}")