# -*- coding: utf-8 -*-
"""mosskin-8 uploaded ver.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDxlKaAAPbXlbQz4jrkz62QIUzhR9hQF
"""

#ver3 frontend movie selection 17/5/26 (Aidan), next is to add personalised pictures under movie dict, and route from json file?
import streamlit as st

st.title("Silver Kampong")
movies = [
        {"title": "My Children", "desc": "A man who values his children", "showtimes": "9.00 AM", "halls": "Cinema Hall 1", "photos": "https://images.pexels.com/photos/15914002/pexels-photo-15914002.jpeg"},
        {"title": "My Struggle", "desc": "Is this source reliable?", "showtimes": "12.00 PM", "halls": "Cinema Hall 2", "photos": "https://images.pexels.com/photos/9804995/pexels-photo-9804995.jpeg"},
        {"title": "-man", "desc": "-I am powerless", "showtimes": "3.00 PM", "halls": "Cinema Hall 3", "photos": "https://images.pexels.com/photos/28344947/pexels-photo-28344947.jpeg"}]

filters = st.selectbox("Filters", options=["All", "Showtimes", "Halls"], index=0)
if filters == "All":
    col1, col2, col3 = st.columns(3, border=True, vertical_alignment="center")

    with col1:
        st.subheader(movies[0]["title"])
        st.caption(movies[0]["desc"])
        st.image(movies[0]["photos"])
        st.write("Showtimes:")
        st.link_button(movies[0]["showtimes"], "https://www.gv.com.sg/")
        st.write("halls:")
        st.link_button(movies[0]["halls"], "https://www.gv.com.sg/")

    with col2:
        st.subheader(movies[1]["title"])
        st.caption(movies[1]["desc"])
        st.image(movies[1]["photos"])
        st.write("Showtimes:")
        st.link_button(movies[1]["showtimes"], "https://www.gv.com.sg/")
        st.write("halls:")
        st.link_button(movies[1]["halls"], "https://www.gv.com.sg/")

    with col3:
        st.subheader(movies[2]["title"])
        st.caption(movies[2]["desc"])
        st.image(movies[2]["photos"])
        st.write("Showtimes:")
        st.link_button(movies[2]["showtimes"], "https://www.gv.com.sg/")
        st.write("halls:")
        st.link_button(movies[2]["halls"], "https://www.gv.com.sg/")
elif filters == "Showtimes":
    showtimes = [movies[0]["showtimes"], movies[1]["showtimes"], movies[2]["showtimes"]]

    showtimes_filter = st.pills("", options=showtimes, default=showtimes, selection_mode="multi")

    filtered_movies = []
    for m in movies:
            if m["showtimes"] in showtimes_filter:
                    filtered_movies.append(m)

    if filtered_movies:
        cols = st.columns(len(filtered_movies), border=True, vertical_alignment="center")
        for col, movie in zip(cols, filtered_movies):
            with col:
                st.subheader(movie["title"])
                st.caption(movie["desc"])
                st.image(movie["photos"])
                st.write("Showtimes:")
                st.link_button(movie["showtimes"], "https://www.gv.com.sg/")
                st.write("halls:")
                st.link_button(movie["halls"], "https://www.gv.com.sg/")

elif filters == "Halls":
    halls = [movies[0]["halls"], movies[1]["halls"], movies[2]["halls"]]

    halls_filter = st.pills("", options=halls, default=halls, selection_mode="multi")

    filtered_movies = []
    for m in movies:
            if m["halls"] in halls_filter:
                    filtered_movies.append(m)

    if halls_filter:
        cols = st.columns(len(filtered_movies), border=True, vertical_alignment="center")
        for col, movie in zip(cols, filtered_movies):
            with col:
                st.subheader(movie["title"])
                st.caption(movie["desc"])
                st.image(movie["photos"])
                st.write("Halls:")
                st.link_button(movie["halls"], "https://www.gv.com.sg/")
                st.write("Showtimes:")
                st.button(movie["showtimes"], "https://www.gv.com.sg/")